name: IVI SDK CSharp - CI

on:
  push:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      
      - name: Run build script      
        run: .\_build\Execute-Psake.ps1 -task_file Build -task_name publish
        shell: pwsh
        env:
          ASPNETCORE_ENVIRONMENT: Development

      - name: Test Report 
        uses: dorny/test-reporter@v1
        if: always()   # run this step even if previous step failed
        with:
          name: XUnit Tests            # Name of the check run which will be created
          path: BuildArtifacts/TestResults/TestResults.trx    # Path to test results
          reporter: dotnet-trx        # Format of test results

      - name: 'Publish Test Report'
        if: always()
        uses: actions/upload-artifact@v2-preview
        with:
          name: 'report'
          path: BuildArtifacts/*
